# Generated by Django 5.0.7 on 2024-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.CharField(max_length=20)),
                ('product_id', models.IntegerField()),
                ('product_title', models.CharField(max_length=100)),
                ('product_image_url', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=50)),
                ('store_id', models.IntegerField()),
                ('sales_per_day', models.IntegerField()),
            ],
        ),
    ]
